---
title: "FADD Data"
author: "WAK"
format: html
editor: visual
---

```{r}
#| include: false
#| warning: false
#| echo: false

library(epiDisplay)
library(knitr)
library(pROC)
library(tidyverse)
library(readxl)
library(ggplot2)
library(gmodels)
library(ggbeeswarm)
library(dplyr)
library(readr)
library(ggpubr)
library(psych)
library(lme4)
library(Matrix)
library(lmerTest)
library(irr)
library(lmerTest)
library(emmeans)
library(doBy)       
library(gmodels)    
library(car)           
library(cowplot)       
library(gridGraphics)  
library(multcomp)
library(hms)
library(gt)
library(lubridate)
library(nlme)
library(extrafont)
```

#### Data Steps

```{r}

sheeps <- read_excel("data/TPI Data.xlsx", sheet = "Farm 1 - Sheep")
goats <- read_excel("data/TPI Data.xlsx", sheet = "Farm 2 - Goats")
calf1 <- read_excel("data/TPI Data.xlsx", sheet = "Farm 3 - Dairy + Beef")
calf2 <- read_excel("data/TPI Data.xlsx", sheet = "Farm 4 - Calf Depot")


```

## Sheep

```{r}


sheeps |> 
  ggplot(mapping=aes(STP))+
  theme_classic()+
  geom_histogram(binwidth=0.5, 
                 fill="purple3", 
                 color="black", 
                 alpha=0.7)+
  labs(title = "Histogram of STP - SHEEP")


#create categories

sheeps<-sheeps %>% 
  mutate(levels = 
           case_when (
             STP <=5.1 ~ "LOW", 
             STP > 5.1 ~ "ADEQUATE"))

sheeps %>% 
  group_by(levels) %>% 
  count()


```

## Goats

```{r}

goats |> 
  ggplot(mapping=aes(STP))+
  theme_classic()+
  geom_histogram(binwidth=0.5, 
                 fill="pink", 
                 color="black", 
                 alpha=0.7)+
  labs(title = "Histogram of STP - GOATS")


#create categories

goats<-goats %>% 
  mutate(levels = 
           case_when (
             STP <=5.1 ~ "LOW", 
             STP > 5.1 ~ "ADEQUATE"))

goats %>% 
  group_by(levels) %>% 
  count()

```

## Calf - One Dairy

```{r}

calf1 |> 
  ggplot(mapping=aes(STP))+
  theme_classic()+
  geom_histogram(binwidth=0.5, 
                 fill="red4", 
                 color="black", 
                 alpha=0.7)+
  labs(title = "Histogram of STP - Calf1")


#create categories

calf1<-calf1 %>% 
  mutate(levels = 
           case_when (
             STP < 5.1               ~ "Poor",
             STP >= 5.1 & STP <= 5.7 ~ "Fair",
             STP >= 5.8 & STP <= 6.1 ~ "Good",
             STP >= 6.2              ~ "Excellent"))


calf1 %>% 
  group_by(levels) %>% 
  count()


calf1 %>% 
  group_by (sex, levels) %>% 
  count()

calf1 %>% 
  group_by (Breed, levels) %>% 
  count()

```

## Calf 2 - DEPOT

```{r}
calf2 |> 
  ggplot(mapping=aes(STP))+
  theme_classic()+
  geom_histogram(binwidth=0.5, 
                 fill="blue4", 
                 color="black", 
                 alpha=0.7)+
  labs(title = "Histogram of STP - Calf2")


#create categories

calf2<-calf2 %>% 
  mutate(levels = 
           case_when (
             STP < 5.1               ~ "Poor",
             STP >= 5.1 & STP <= 5.7 ~ "Fair",
             STP >= 5.8 & STP <= 6.1 ~ "Good",
             STP >= 6.2              ~ "Excellent"))


calf2 %>% 
  group_by(levels) %>% 
  count()


calf2 %>% 
  group_by(SourceFarm) %>% 
  count()


calf2 %>% 
  group_by(SourceFarm, levels) %>% 
  count()



```
